import type { Car } from "@workspace/bilcost-pricing";
import type { ListingPreview } from "./types";

/**
 * Curated set of sample Danish car listings used as fallback search
 * results and as the seed dataset for offline demos. Real Bilbasen
 * listing URLs are referenced for traceability; details may be slightly
 * idealised. The fields are the exact ones the TCO model needs.
 */
export interface SampleEntry extends Car {
  id: string;
}

export const SAMPLE_CATALOG: SampleEntry[] = [
  {
    id: "vw-id3-2025-new",
    make: "Volkswagen",
    model: "ID.3",
    variant: "Pro 58 kWh",
    year: 2025,
    mileageKm: 0,
    priceDkk: 339_900,
    fuelType: "electric",
    consumptionKmPerL: null,
    consumptionKwhPer100km: 15.8,
    co2Gkm: 0,
    kerbWeightKg: 1_812,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/volkswagen/id-3",
    imageUrl: null,
  },
  {
    id: "vw-id3-2021-used",
    make: "Volkswagen",
    model: "ID.3",
    variant: "Pro Performance 58 kWh",
    year: 2021,
    mileageKm: 62_000,
    priceDkk: 199_900,
    fuelType: "electric",
    consumptionKmPerL: null,
    consumptionKwhPer100km: 16.5,
    co2Gkm: 0,
    kerbWeightKg: 1_812,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/volkswagen/id-3",
    imageUrl: null,
  },
  {
    id: "tesla-m3-2025-new",
    make: "Tesla",
    model: "Model 3",
    variant: "Long Range AWD",
    year: 2025,
    mileageKm: 0,
    priceDkk: 419_900,
    fuelType: "electric",
    consumptionKmPerL: null,
    consumptionKwhPer100km: 14.6,
    co2Gkm: 0,
    kerbWeightKg: 1_847,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/tesla/model-3",
    imageUrl: null,
  },
  {
    id: "tesla-m3-2020-used",
    make: "Tesla",
    model: "Model 3",
    variant: "Long Range AWD",
    year: 2020,
    mileageKm: 95_000,
    priceDkk: 229_000,
    fuelType: "electric",
    consumptionKmPerL: null,
    consumptionKwhPer100km: 15.5,
    co2Gkm: 0,
    kerbWeightKg: 1_847,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/tesla/model-3",
    imageUrl: null,
  },
  {
    id: "vw-golf-2025-new",
    make: "Volkswagen",
    model: "Golf",
    variant: "1.5 eTSI 150 Style DSG",
    year: 2025,
    mileageKm: 0,
    priceDkk: 339_900,
    fuelType: "petrol",
    consumptionKmPerL: 19.2,
    consumptionKwhPer100km: null,
    co2Gkm: 119,
    kerbWeightKg: 1_410,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/volkswagen/golf",
    imageUrl: null,
  },
  {
    id: "vw-golf-2019-used",
    make: "Volkswagen",
    model: "Golf",
    variant: "1.5 TSI 150 Highline",
    year: 2019,
    mileageKm: 110_000,
    priceDkk: 169_900,
    fuelType: "petrol",
    consumptionKmPerL: 17.5,
    consumptionKwhPer100km: null,
    co2Gkm: 130,
    kerbWeightKg: 1_375,
    transmission: "manual",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/volkswagen/golf",
    imageUrl: null,
  },
  {
    id: "skoda-octavia-2025-new",
    make: "Skoda",
    model: "Octavia",
    variant: "1.5 TSI 150 Style DSG",
    year: 2025,
    mileageKm: 0,
    priceDkk: 359_900,
    fuelType: "petrol",
    consumptionKmPerL: 18.5,
    consumptionKwhPer100km: null,
    co2Gkm: 122,
    kerbWeightKg: 1_443,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/skoda/octavia",
    imageUrl: null,
  },
  {
    id: "skoda-octavia-2018-used",
    make: "Skoda",
    model: "Octavia",
    variant: "2.0 TDI 150 Style DSG",
    year: 2018,
    mileageKm: 145_000,
    priceDkk: 144_900,
    fuelType: "diesel",
    consumptionKmPerL: 22.0,
    consumptionKwhPer100km: null,
    co2Gkm: 110,
    kerbWeightKg: 1_465,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/skoda/octavia",
    imageUrl: null,
  },
  {
    id: "toyota-yaris-2024-new",
    make: "Toyota",
    model: "Yaris",
    variant: "1.5 Hybrid Active e-CVT",
    year: 2024,
    mileageKm: 0,
    priceDkk: 219_900,
    fuelType: "hybrid",
    consumptionKmPerL: 25.0,
    consumptionKwhPer100km: null,
    co2Gkm: 92,
    kerbWeightKg: 1_120,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/toyota/yaris",
    imageUrl: null,
  },
  {
    id: "toyota-yaris-2017-used",
    make: "Toyota",
    model: "Yaris",
    variant: "1.5 Hybrid H2",
    year: 2017,
    mileageKm: 130_000,
    priceDkk: 89_900,
    fuelType: "hybrid",
    consumptionKmPerL: 23.0,
    consumptionKwhPer100km: null,
    co2Gkm: 100,
    kerbWeightKg: 1_085,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/toyota/yaris",
    imageUrl: null,
  },
  {
    id: "bmw-330e-2025-new",
    make: "BMW",
    model: "3-serie",
    variant: "330e xDrive M-Sport",
    year: 2025,
    mileageKm: 0,
    priceDkk: 729_900,
    fuelType: "phev",
    consumptionKmPerL: 17.0,
    consumptionKwhPer100km: 18.0,
    co2Gkm: 36,
    kerbWeightKg: 1_795,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/bmw/3-serie",
    imageUrl: null,
  },
  {
    id: "bmw-330e-2020-used",
    make: "BMW",
    model: "3-serie",
    variant: "330e Sport Line",
    year: 2020,
    mileageKm: 105_000,
    priceDkk: 339_900,
    fuelType: "phev",
    consumptionKmPerL: 16.5,
    consumptionKwhPer100km: 19.5,
    co2Gkm: 41,
    kerbWeightKg: 1_790,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/bmw/3-serie",
    imageUrl: null,
  },
  {
    id: "kia-niro-ev-2025-new",
    make: "Kia",
    model: "Niro EV",
    variant: "Upgrade 64 kWh",
    year: 2025,
    mileageKm: 0,
    priceDkk: 339_900,
    fuelType: "electric",
    consumptionKmPerL: null,
    consumptionKwhPer100km: 16.2,
    co2Gkm: 0,
    kerbWeightKg: 1_739,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/kia/niro",
    imageUrl: null,
  },
  {
    id: "kia-niro-2019-used",
    make: "Kia",
    model: "Niro",
    variant: "1.6 GDi Hybrid Vision DCT",
    year: 2019,
    mileageKm: 120_000,
    priceDkk: 154_900,
    fuelType: "hybrid",
    consumptionKmPerL: 22.0,
    consumptionKwhPer100km: null,
    co2Gkm: 105,
    kerbWeightKg: 1_504,
    transmission: "automatic",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/kia/niro",
    imageUrl: null,
  },
  {
    id: "peugeot-208-2024-new",
    make: "Peugeot",
    model: "208",
    variant: "1.2 PureTech 100 Allure",
    year: 2024,
    mileageKm: 0,
    priceDkk: 209_900,
    fuelType: "petrol",
    consumptionKmPerL: 19.6,
    consumptionKwhPer100km: null,
    co2Gkm: 117,
    kerbWeightKg: 1_135,
    transmission: "manual",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/peugeot/208",
    imageUrl: null,
  },
  {
    id: "peugeot-208-2018-used",
    make: "Peugeot",
    model: "208",
    variant: "1.2 PureTech 82 Active",
    year: 2018,
    mileageKm: 115_000,
    priceDkk: 79_900,
    fuelType: "petrol",
    consumptionKmPerL: 20.0,
    consumptionKwhPer100km: null,
    co2Gkm: 110,
    kerbWeightKg: 1_090,
    transmission: "manual",
    listingUrl: "https://www.bilbasen.dk/brugt/bil/peugeot/208",
    imageUrl: null,
  },
];

export function listingPreview(c: SampleEntry): ListingPreview {
  return {
    id: c.id,
    make: c.make,
    model: c.model,
    variant: c.variant,
    year: c.year,
    mileageKm: c.mileageKm,
    priceDkk: c.priceDkk,
    fuelType: c.fuelType,
    imageUrl: c.imageUrl,
    listingUrl: c.listingUrl ?? "",
  };
}
